### ISSUE TITLE
Check for existing PDF software installed on the user's device

### ISSUE THREAD

**Issue by tomgrim** [doctorapps/nhs_android#12]

**Comment by robgledhill** [comment]
I'm happy to try and tackle this one

**Comment by robgledhill** [comment]
@tomgrim I've worked out how to get a list of all the applications already installed on the phone - and I've asked a load of friends with android phones which applications they have that can open PDFs

**Comment by robgledhill** [comment]
This link has helped me work out how to get the list:
http://stackoverflow.com/questions/2695746/how-to-get-a-list-of-installed-android-applications-and-pick-one-to-run

**Comment by robgledhill** [comment]
I've found a better way - just testing it out

**Comment by robgledhill** [comment]
@tomgrim Added this functionality - and done the ol' push/pull

Do you want to check this, or are you happy for me to close this issue?

**Comment by tomgrim** [comment]
@robgledhill nice one! I'll check out the work and close the issue once it's in master :+1:
