### ISSUE TITLE
Get android studio running

### ISSUE THREAD

**Issue by tomgrim** [doctorapps/nhs_android#2]
@jshadwel 
- [x] You will need java to complete the install.
- [x] Install android studio
- [x] Install git
- [x] Clone the repository
- [x] Get emulator up and running

@robgledhill 
- [x] You will need java to complete the install.
- [x] Install android studio
- [x] Install git
- [x] Clone the repository
- [x] Get emulator up and running

Final product should look like this:
![screen shot 2015-10-28 at 14 05 40](https://cloud.githubusercontent.com/assets/1646456/10791015/64afc05c-7d7e-11e5-8607-02c79e36d273.png)

**Comment by jshadwel** [comment]
thanks tom
downloaded the relevant software -- took ages!
did elementary github tutorial. still not sure how it works but making slow progress
will attempt to obtain emulator to clone repository

**Comment by robgledhill** [comment]
Boom.  Thanks Tom!  Got the software up and running

Jonny - the final two steps are by far the easiest

**Comment by jshadwel** [comment]
I am more computer illiterate than I thought, sorry.
I don't know how to mark the tasks as complete (tick the boxes)
and I don't know how to complete part 4 and 5

**Comment by robgledhill** [comment]
@jshadwel 
To mark the boxes as complete I just clicked on them in Tom's comment

To do step 4 go to the home page for the app (https://github.com/doctorapps/nhs_android)

In the right hand column click clone repository

I'll finish this comment later - laptop out of battery and just found out my charger has become the victim of a shaving cream explosion in my suitcase

**Comment by robgledhill** [comment]
Saved!  Compatible with my work laptop charger.

Anyway after you've clicked "clone repository" you should see an option to download an application called something like "GitHub desktop" - do this download and there will then be a tutorial on how to clone.  After you've done the tutorial there will be an option to clone the NHS_Android app.  (You can only do it for the first time once, so I can't walk through the steps again to check, as a result I may have missed some info, sorry)

**Comment by tomgrim** [comment]
@jshadwel I made rob an admin but hadnt given you any new permissions yet so you couldn't edit my initial post, oops. You should be able to mark things off now.

As for android studio: 

1. First you need to click `Check out project from version control`

![screen shot 2015-11-02 at 21 54 26](https://cloud.githubusercontent.com/assets/1646456/10895498/760bb68a-81ac-11e5-96fc-4ef24e882615.png)

2. Then click `github`
3. Add your username and password here

![screen shot 2015-11-02 at 21 56 16](https://cloud.githubusercontent.com/assets/1646456/10895515/9c10efb2-81ac-11e5-8c8d-9344cc7621b1.png)

4. Clone the repo as I have below, you'll want to find your AndroidStudio folder, it will probably already be set.

![screen shot 2015-11-02 at 21 57 50](https://cloud.githubusercontent.com/assets/1646456/10895552/cebbfe52-81ac-11e5-8766-0a42ebe61950.png)

5. Press `clone`. Voila!

**Comment by robgledhill** [comment]
As for the emulator:
1) Open android studio
2) Open Tools/Android/AVD Manager   (AVD = android virtual device = emulator)
3) Click "Create Virtual Device"
4) Select the phone you want
5) Bada bing bada boom - you're done

This probably won't work first time - but whenever you encounter an error just google the error message and there's usually someone helpfully explaining what's gone wrong

**Comment by robgledhill** [comment]
@tomgrim Man this shows the danger of working things out for yourself - I'd managed to clone the repository, and I think the integration more or less worked - but your way is LOADS better.

**Comment by robgledhill** [comment]
@jshadwel if you can't find how to do an action in Android Studio press ctrl+shift+a which will then let you "find action"

**Comment by jshadwel** [comment]
many thanks. I clicked some boxes so i feel like I've made progress

I seem to be here.
![image](https://cloud.githubusercontent.com/assets/15332352/10896049/651f1080-81af-11e5-97a5-fd5e5531563e.png)

- @robgledhill only the nexus to choose but it doesn't run, I have this error message
C:\Users\Jonny\AppData\Local\Android\sdk\tools\emulator.exe -avd Nexus_5_API_23_x86 -netspeed full -netdelay none
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure Intel HAXM is properly installed and usable.
CPU acceleration status: HAX kernel module is not installed!

android sdk manager is now in the process of slowly downloading seven "packages"

**Comment by jshadwel** [comment]
ps I am sure that explaining all this to a n00b must be slow and infuriating, soz. Im not a quitter but I dont expect you guys to waste time dragging me through the process since i'm unlikely to contribute much anyway. I'm going to keep trying to learn some of this using the internet

pps I'll be away in france for the next few days on annual leave so my slow progress will be even slower

**Comment by robgledhill** [comment]
So this website gives instructions on how to download HAXM emulator https://software.intel.com/en-us/android/articles/installation-instructions-for-intel-hardware-accelerated-execution-manager-windows

I remember when I first tried it I forgot to perform step 6 "Run the installer inside the <sdk folder>/sdk/extras/intel/Hardware_Accelerated_Execution_Manager/ directory and follow the installation instructions for your platform." 

It means you download it with the SDK manager, but you then need to locate in in windows explorer and run the application for the install to complete.

**Comment by tomgrim** [comment]
@jshadwel I ran into the same problem on windows. I didn't bother solving it because it was running fine on my macbooks. I'll see if I can get it running with @robgledhill 's link.

enjoy :fr:

**Comment by tomgrim** [comment]
@robgledhill @jshadwel I got round the problem by using an AMD emulator. I just downloaded Genymotion though and it runs the app in under a second whereas it was taking a couple of minutes using the emulator bundled with android studio.
