### ISSUE TITLE
native PDF viewer

### ISSUE THREAD

**Issue by tomgrim** [doctorapps/nhs_android#3]
http://stackoverflow.com/questions/2456344/display-pdf-within-app-on-android

First attempt here: https://github.com/doctorapps/nhs_android/pull/5 using the android `PdfRenderer` class. Problem at the moment is I think the android build process is compressing the assets so need to uncompress/load into cache before attempting to render.

This class is only available in the more recent APIs too. (Think 21+) I thought we should support versions 15+ (which I think is about 98% of android devices) but maybe it's better to just support the most recent versions using the official android pdf renderer? 

There is a library to support lower versions of PDFs but I haven't even attempted that one yet.

Might also need to look into pdfs in a webview. 

**Flow**:

1. Check for PDF application installed on device
2. If present, open using that.
3. If not present… use webview?

**Comment by tomgrim** [comment]
What do you lot think about which versions of android we should be supporting? As many devices as possible or the more recent android versions so we can use more recent libraries? @jshadwel @robgledhill

**Comment by robgledhill** [comment]
There really aren't many phones that last longer for 3 years - if we take a version of android about 3 years old we should have pretty much everything covered?  What do you think?

**Comment by jshadwel** [comment]
i agree with rob. many devices would be useful but versions>3years old are unlikely to be common

**Comment by tomgrim** [comment]
After doing a bit more reading into the android ecosystem I don't think this is as great a problem as I first imagined. Android apps can access other apps to do jobs for them which should be very helpful. So if a user has a PDF reader on their phone like Adobe PDF Reader we can use it to render our PDFs.

This gave me an idea for a kind of graceful degradation. Initially we try and find a PDF application. If no application is installed we use the official android PDF reader. If a user doesnt have a phone capable of using the official PDF reader either… we can just ask them to download a 3rd party app?

I think for an alpha version that should give us quite a lot of support. I have no idea how many devices would fail both of these requirements and not be able to install a 3rd party PDF reader but I imagine it must be very small. We could potentially think about packaging our own PDF reader written in C or the lower level PDF readers as a further backup in future.

@robgledhill do you have a PDF reader app on your phone? I think a sample size of 1 should be large enough to confirm the above.

**Comment by robgledhill** [comment]
@tomgrim 
So I've got two android phones - my work and my personal one.

I have :
Drive PDF Viewer
POLARIS Office Viewer
A dropbox pdf viewer

I do remember that I had to install a pdf viewer when I took my personal phone out the box, but that phone is almost 3 years old now

**Comment by tomgrim** [comment]
That's good to hear. So hopefully it won't be too shocking to users if we're asking them to download other apps to view the files with.
