### ISSUE TITLE
List of PDF files

### ISSUE THREAD

**Issue by tomgrim** [doctorapps/nhs_android#6]
Could we get an array of file names on the main screen @robgledhill ?

Dont have to do anything, just display

**Comment by robgledhill** [comment]
Can do

**Comment by robgledhill** [comment]
Hey @tomgrim 
Think I've finished this - can we have a phonecall before I do the first check in - as I'm a bit nervous about accidentally overwriting your data.

**Comment by tomgrim** [comment]
@robgledhill sure thing - when suits? Don't worry too much about overwriting my data, git is decentralised so everything will still be on my machine.

**Comment by robgledhill** [comment]
@tomgrim Weds evening suit you?

**Comment by tomgrim** [comment]
@robgledhill sure, around 8:00-9:00 if possible.

**Comment by robgledhill** [comment]
2000 sounds good

**Comment by tomgrim** [comment]
So rob want to try and…
- Create a new branch
  The bottom right hand side of android studio you should see a little sign which says `Git: <branch name>` on it. 
![screen shot 2015-11-04 at 20 44 48](https://cloud.githubusercontent.com/assets/1646456/10951350/f4f57f10-8334-11e5-8aa6-dd6c7a1afd58.png)
![screen shot 2015-11-04 at 20 45 22](https://cloud.githubusercontent.com/assets/1646456/10951393/51026188-8335-11e5-9866-2ae425c2dbba.png)
![screen shot 2015-11-04 at 20 45 35](https://cloud.githubusercontent.com/assets/1646456/10951394/5103dda6-8335-11e5-8a78-5bb78feea62a.png)

- Commit your changes into that branch (add a descriptive message)
![screen shot 2015-11-04 at 20 46 23](https://cloud.githubusercontent.com/assets/1646456/10951392/51015dce-8335-11e5-9750-14a071f0dd8a.png)
- Push your changes to github (commit and push button)
- Create a pull request back into master 
  if you've pushed go to the home of the git repo on github and you should see your new branch has been pushed up.
  
![screen shot 2015-11-04 at 20 50 40](https://cloud.githubusercontent.com/assets/1646456/10951502/cc6fb712-8335-11e5-9742-5c33a3a9d24d.png)

![screen shot 2015-11-04 at 20 51 38](https://cloud.githubusercontent.com/assets/1646456/10951519/df5c1ac8-8335-11e5-9cc8-f6bd165f5850.png)

@robgledhill let me know if you get stuck!

**Comment by robgledhill** [comment]
Done!  Issue closed
